inherit_from: .rubocop_todo.yml
require: rubocop-rspec
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - app/controllers/pieces_controller.rb
Documentation:
  Enabled: false
